name: SQL CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Set up database schema
        run: |
          for file in sql/tables/*.sql; do
            psql $DATABASE_URL -f "$file"
          done

      - name: Insert sample data
        run: psql $DATABASE_URL -f sql/data.sql

      - name: Verify data
        run: psql $DATABASE_URL -f sql/verify.sql
